# Generated by Django 4.1.7 on 2023-03-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0003_dueño_alter_mascotas_ciudad_mascotas_dueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='codigo',
            field=models.AutoField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
