# Generated by Django 4.1.7 on 2023-03-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0004_alter_dueño_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
