# Generated by Django 4.1.7 on 2023-03-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0005_alter_dueño_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='codigo',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
