# Generated by Django 4.1.7 on 2023-03-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0007_alter_dueño_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dueño',
            old_name='codigo',
            new_name='auto_increment_id',
        ),
    ]
